markdown: kramdown

title: bastianluk
description: the hub
author:
  name: Lukas Bastian

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
