markdown: kramdown

url: "https://bastianluk.github.io/"
baseurl: ""
title: bastianluk
description: the hub
author:
  name: Lukas Bastian

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
